def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    # config.add_route('options_handling', '/{catch_all:.*}',
    #                  request_method="OPTIONS")
    config.add_route('home', '/')
    config.add_route('event_list', '/event_list')
    config.add_route('event', '/event_list/{id}')
    config.add_route('ajax_order', '/ajax/order')
    config.add_route('ajax_mailto', '/ajax/mailto')
    config.add_route('admin_login', '/admin/login')
    config.add_route('admin_logout', '/admin/logout')
    config.add_route('admin_archive', '/admin/archive')
    config.add_route('admin_payouts', '/admin/payouts')
    config.add_route('admin_setting', '/admin/setting')
    config.add_route('admin_trash', '/admin/trash')
    config.add_route('admin_team', '/admin/team')
    config.add_route('admin', '/admin')
    config.add_route('checkout', '/checkout')
    config.add_route('checkout_success', '/checkout/success')
    config.add_route('checkout_fail', '/checkout/fail')
